---
- hosts: localhost
  become: yes
  vars_files:
    - users.yml
  tasks:
  
  - name: create groups
    group:
      name: Clearlogs
      state: present

  - name: Adding Users
    user: 
      name: "{{ item.name }}"
      create_home: no
      password: "{{ 'password' | password_hash('sha512') }}"
      update_password: on_create
      groups: Clearlogs
    with_items: "{{ users }}"

  - name: Add group to sudo
    copy:
      content: "%Clearlogs ALL=(ALL:ALL) NOPASSWD:ALL"
      dest: /etc/sudoers.d/020_Clearlogs-nopasswd
      mode: 0440 

  - name: Create directory
    file:
      path: /home/scriptadmin/test
      state: directory
      owner: "{{ item.name }}"
      group: Clearlogs
      mode: 0775
    with_items: "{{ users }}"

  - name: Run Cleanup Script
    script: /home/ubuntu/bede_tech/scripts/space.sh

  - name: Set Cron job for space script
    cron:
      name: "Clear Logs"
      user: "scriptadmin"
      hour: 23
      job: "/home/ubuntu/bede_tech/scripts/space.sh"
