---
- hosts: localhost
  become: yes
  vars_files:
    - users.yml
  
  tasks:
  
  - name: create groups
    group:
      name: Clearlogs
      state: present

  - name: Adding Users
    user: 
      name: "{{ item.name }}"
      create_home: yes
      password: "{{ 'password' | password_hash('sha512') }}"
      update_password: on_create
      groups: Clearlogs
    with_items: "{{ users }}"

  - name: Add group to sudo
    copy:
      content: "%Clearlogs ALL=(ALL:ALL) NOPASSWD:ALL"
      dest: /etc/sudoers.d/020_Clearlogs-nopasswd
      mode: 0440 

  - name: create directory if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: scriptadmin
      group: Clearlogs
      mode: 0775
    with_items:
    - /home/scriptadmin/test
    - /home/scriptadmin/scripts

  - name: copy script to directory
    copy: 
      src: ~/bede_tech/scripts/space.sh
      dest: /home/scriptadmin/scripts
      owner: scriptadmin
      group: Clearlogs
      mode: 0775

  - name: Set Cron job for space script
    cron:
      name: "Clear Logs"
      user: "scriptadmin"
      hour: 23
      job: "/home/scriptadmin/scripts/space.sh"
